import { Header } from "@/components/header/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="flex w-full flex-col max-w-7xl m-auto p-8 mt-8">
        {children}
      </div>
    </>
  );
}
